[Perf](data painter): Stronger Painter Supporting 100K Records of data
Kanaries/Rath pull request #336
Opened 2023-04-15 19:28 UTC by k6sdevbob

2023-04-20 08:57 UTC, Asm-Def commented on packages/rath-client/src/pages/painter/index.tsx
> +                                // TODO: directly setting 'fill' of scenegraph
[DELETE THIS] already done

2023-04-21 10:29 UTC, ObservedObserver requested changes

2023-04-21 10:29 UTC, ObservedObserver commented on packages/rath-client/src/pages/painter/index.tsx
> +                            for (let f of limitFields) {
Mark

2023-04-21 10:29 UTC, ObservedObserver commented on packages/rath-client/src/pages/painter/index.tsx
> +                                newColor: COLOR_CELLS[mutFeatIndex].color,
Mark

2023-04-21 13:55 UTC, closed without merging